version: '3.8'

services:
  # PostgreSQL 数据库 (优化内存使用)
  postgres:
    image: postgres:15-alpine
    container_name: groupup-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your-super-secure-password}
      POSTGRES_DB: postgres
      # 内存优化设置
      POSTGRES_SHARED_BUFFERS: 128MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 256MB
      POSTGRES_WORK_MEM: 2MB
      POSTGRES_MAINTENANCE_WORK_MEM: 32MB
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init_database.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # PostgREST API (轻量级)
  rest:
    image: postgrest/postgrest:v11.2.0
    container_name: groupup-rest
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:${POSTGRES_PASSWORD:-your-super-secure-password}@postgres:5432/postgres
      PGRST_DB_SCHEMA: public,storage
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: "false"
      PGRST_DB_POOL: 10
      PGRST_DB_POOL_TIMEOUT: 3600
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # GoTrue 认证服务 (轻量级)
  auth:
    image: supabase/gotrue:v2.132.3
    container_name: groupup-auth
    restart: unless-stopped
    ports:
      - "9999:9999"
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-your-super-secure-password}@postgres:5432/postgres?search_path=auth
      GOTRUE_SITE_URL: ${SITE_URL:-http://localhost:3000}
      GOTRUE_URI_ALLOW_LIST: ${ALLOWED_URLS:-http://localhost:3000}
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_EXTERNAL_EMAIL_ENABLED: true
      GOTRUE_SMTP_HOST: ${SMTP_HOST}
      GOTRUE_SMTP_PORT: ${SMTP_PORT:-587}
      GOTRUE_SMTP_USER: ${SMTP_USER}
      GOTRUE_SMTP_PASS: ${SMTP_PASS}
      GOTRUE_SMTP_ADMIN_EMAIL: ${SMTP_ADMIN_EMAIL}
      GOTRUE_MAILER_AUTOCONFIRM: ${MAILER_AUTOCONFIRM:-true}
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Storage 服务 (轻量级)
  storage:
    image: supabase/storage-api:v0.43.11
    container_name: groupup-storage
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      POSTGREST_URL: http://rest:3000
      PGRST_JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-your-super-secure-password}@postgres:5432/postgres
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: groupup
      REGION: local
      GLOBAL_S3_BUCKET: groupup-storage
      # 禁用图片转换以节省内存
      ENABLE_IMAGE_TRANSFORMATION: "false"
    volumes:
      - storage-data:/var/lib/storage
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Nginx 反向代理 (超轻量)
  nginx:
    image: nginx:alpine
    container_name: groupup-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.lite.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - rest
      - auth
      - storage
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

volumes:
  postgres-data:
  storage-data: